import os, json, smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from dotenv import load_dotenv
load_dotenv()

DEFAULT_MAP = {
    "Payments Team":"payments@yourco.com","QA Payments":"qa@yourco.com",
    "Platform Team":"platform@yourco.com","Release Manager":"release@yourco.com",
    "Security Team":"security@yourco.com","Backend Team":"backend@yourco.com",
    "DBA Team":"dba@yourco.com","QA Lead":"qalead@yourco.com",
}

def send_team_notifications(result: dict) -> list:
    ia     = result.get("Impact Analysis",{})
    ri     = result.get("Release Intelligence",{})
    rv     = result.get("PR Review",{})
    teams  = list(set(ia.get("impacted_teams",[]) + ri.get("suggested_stakeholders",[])))

    try: emap = json.loads(os.getenv("NOTIFY_EMAIL_MAP","{}"))
    except: emap = {}
    emap = {**DEFAULT_MAP, **emap}

    smtp_user = os.getenv("SMTP_USER","")
    smtp_pass = os.getenv("SMTP_PASS","")
    smtp_host = os.getenv("SMTP_HOST","smtp.gmail.com")
    smtp_port = int(os.getenv("SMTP_PORT","587"))

    notified = []
    for team in teams:
        email = emap.get(team)
        if not email:
            notified.append({"team":team,"status":"no_email"}); continue
        subject = f"[Agent Zed] PR #{result.get('pr_id')} {result.get('event_type','').upper()} — {result.get('title','')}"
        body    = _html(result, team, rv, ia, ri)
        status  = _send(smtp_host, smtp_port, smtp_user, smtp_pass, smtp_user, email, subject, body)
        notified.append({"team":team,"email":email,"status":status})
        print(f"  📧 {team} → {status}")
    return notified

def _send(host,port,user,pw,frm,to,subj,body):
    if not user or not pw: return "skipped_no_smtp"
    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"]=subj; msg["From"]=frm; msg["To"]=to
        msg.attach(MIMEText(body,"html"))
        with smtplib.SMTP(host,port,timeout=10) as s:
            s.ehlo(); s.starttls(); s.login(user,pw); s.sendmail(frm,to,msg.as_string())
        return "sent"
    except Exception as e:
        return f"failed:{e}"

def _html(result, team, rv, ia, ri):
    risk  = rv.get("risk_level","Unknown")
    color = {"High":"#e53e3e","Medium":"#dd6b20","Low":"#38a169"}.get(risk,"#718096")
    files = "".join(f"<li><code>{f}</code></li>" for f in result.get("files_changed",[]))
    teams = "".join(f"<li>{t}</li>" for t in ia.get("impacted_teams",[]))
    return f"""<html><body style="font-family:Arial;max-width:600px;margin:auto;">
<div style="background:#1a202c;padding:20px;border-radius:8px 8px 0 0;">
  <h2 style="color:#fff;margin:0;">🤖 Agent Zed — PR Intelligence</h2>
</div>
<div style="background:#f7fafc;padding:24px;border:1px solid #e2e8f0;">
  <p><b>PR #{result.get('pr_id')}</b>: {result.get('title')}</p>
  <p>Author: {result.get('author')} | Event: {result.get('event_type','').upper()}</p>
  <p>Risk: <span style="background:{color};color:#fff;padding:2px 8px;border-radius:10px;">{risk}</span></p>
  <h3>📁 Files Changed</h3><ul>{files}</ul>
  <h3>🎯 Impacted Teams</h3><ul>{teams}</ul>
  <h3>⚡ Precaution</h3><p>{ri.get('precaution','')}</p>
  <p style="margin-top:20px;">
    <a href="{result.get('pr_url','#')}" style="background:#4c51bf;color:#fff;padding:10px 20px;border-radius:6px;text-decoration:none;">
      View PR on GitHub →
    </a>
  </p>
</div>
<div style="background:#edf2f7;padding:12px;text-align:center;font-size:12px;color:#718096;">
  Generated by Agent Zed AI | Notified: {team}
</div>
</body></html>"""
